import test from 'node:test';import assert from 'node:assert/strict';
import { validatePostCallSemantics, crossValidatePostCallSemantics, validateDefinition } from '../src/contracts.js';import { PostCallExtractor } from '../src/post-call.js';
const ids={u:'u1',a:'a1'};const segs=[{event_id:'u1',speaker:'user',start_ms:1,end_ms:2,phase:'active',delivery:'input_observed',delta:'Передзвоніть у четвер, часовий пояс не знаю; зверніться до Івана +380...'}, {event_id:'a1',speaker:'assistant',start_ms:2,end_ms:3,phase:'active',delivery:'generated_playback_unknown',delta:'Я можу запропонувати передати матеріали команді.'}];
function semantic(){return{role_match:{value:'relevant',evidence_event_ids:[ids.u]},interest:{value:'neutral',evidence_event_ids:[ids.u]},rejection:{value:null,evidence_event_ids:[]},do_not_call:{value:null,evidence_event_ids:[]},next_step:{kind:'callback',status:'proposed',details:'у четвер',evidence_event_ids:[ids.u]},callback:{requested:true,when_text:'у четвер',timezone_text:null,evidence_event_ids:[ids.u]},referral:{person_text:'Іван',role_text:null,phone_text:'+380...',contact_channel_text:null,evidence_event_ids:[ids.u]},questions_for_human:[{text:'Уточнити часовий пояс',evidence_event_ids:[ids.u]}],commitments:[{text:'Запропоновано передати матеріали команді',evidence_event_ids:[ids.a],delivery:'unknown'}],summary:{text:'Контакт попросив передзвонити у четвер.',evidence_event_ids:[ids.u]},confidence:'medium',needs_review:true,review_flags:['delivery_uncertain','ambiguous_callback','referral_unverified']}}
function call(){return{call_id:'00000000-0000-4000-8000-000000000001',contact_id:'00000000-0000-4000-8000-000000000002',company_id:'00000000-0000-4000-8000-000000000003',transcript_state:'captured',transcript_envelope:{sha256:'a'.repeat(64)}}}
function responseFor(obj){return new Response(JSON.stringify({output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(obj)}]}]}),{status:200,headers:{'content-type':'application/json'}})}
test('T35 semantic model cannot inject telephony IDs/outcome/duration/permission facts',()=>{const s={...semantic(),telephony_outcome:'answered'};assert.throws(()=>validatePostCallSemantics(s),/schema validation/);});
test('T36 strict semantic schema rejects unknown fields, wrong enums/types and missing required field',()=>{const extra={...semantic(),x:1};assert.throws(()=>validatePostCallSemantics(extra));const wrong=semantic();wrong.interest.value='very_interested';assert.throws(()=>validatePostCallSemantics(wrong));const missing=semantic();delete missing.summary;assert.throws(()=>validatePostCallSemantics(missing));});
test('T37 cross-validation rejects missing/cross-call/wrong-speaker evidence',()=>{const missing=semantic();missing.interest.evidence_event_ids=['none'];assert.throws(()=>crossValidatePostCallSemantics(missing,segs),/unknown/);const wrong=semantic();wrong.commitments[0].evidence_event_ids=['u1'];assert.throws(()=>crossValidatePostCallSemantics(wrong,segs),/wrong evidence speaker/);});
test('T38 callback/referral preserve raw uncertainty and do not create scheduler/permission actions',()=>{const s=crossValidatePostCallSemantics(semantic(),segs);assert.equal(s.callback.when_text,'у четвер');assert.equal(s.callback.timezone_text,null);assert.equal(s.referral.phone_text,'+380...');assert.equal(s.next_step.status,'proposed');});
test('T39 assistant commitments require assistant evidence and uncertain delivery plus review',()=>{const s=crossValidatePostCallSemantics(semantic(),segs);assert.equal(s.commitments[0].delivery,'unknown');assert.equal(s.needs_review,true);const bad=semantic();bad.commitments[0].delivery='delivered';assert.throws(()=>validatePostCallSemantics(bad));});
test('validated PostCallResult is still needs_review and strict structured output request uses configured model',async()=>{let body;const x=new PostCallExtractor({apiKey:'sk-test',postCallModel:'gpt-4o-mini-2024-07-18'},{fetchImpl:async(_u,o)=>{body=JSON.parse(o.body);return responseFor(semantic())}});const r=await x.extract({call:call(),segments:segs});assert.equal(r.status,'validated');assert.equal(r.needs_review,true);assert.equal(body.store,false);assert.equal(body.text.format.type,'json_schema');assert.equal(body.text.format.strict,true);assert.equal(body.model,'gpt-4o-mini-2024-07-18');});
test('T40 extractor refusal/429/invalid JSON/transport failure keep factual inputs outside result semantics',async()=>{const cfg={apiKey:'sk-test',postCallModel:'model'};const refusal=new PostCallExtractor(cfg,{fetchImpl:async()=>new Response(JSON.stringify({output:[{type:'message',content:[{type:'refusal',refusal:'no'}]}]}),{status:200})});assert.equal((await refusal.extract({call:call(),segments:segs})).status,'refused');const rate=new PostCallExtractor(cfg,{fetchImpl:async()=>new Response('{}',{status:429})});assert.equal((await rate.extract({call:call(),segments:segs})).error_code,'http_429');const bad=new PostCallExtractor(cfg,{fetchImpl:async()=>new Response('{',{status:200})});assert.equal((await bad.extract({call:call(),segments:segs})).error_code,'invalid_json');const net=new PostCallExtractor(cfg,{fetchImpl:async()=>{throw new Error('boom')}});assert.equal((await net.extract({call:call(),segments:segs})).error_code,'network_or_timeout');});
test('PostCallResult contract keeps semantic result separate from immutable factual CallRecord',()=>{const r={result_id:'00000000-0000-4000-8000-000000000010',call_id:call().call_id,contact_id:call().contact_id,company_id:call().company_id,transcript_sha256:'a'.repeat(64),created_at:'2026-10-09T00:00:00.000Z',extractor_model:'m',extractor_prompt_version:'1',schema_version:'1',status:'validated',error_code:null,semantic:semantic(),needs_review:true,review_id:null};assert.doesNotThrow(()=>validateDefinition('PostCallResult',r));});
