import test from 'node:test';import assert from 'node:assert/strict';import { spawn } from 'node:child_process';import { randomUUID } from 'node:crypto';import { copyFileSync, statSync } from 'node:fs';
import { VoiceStore } from '../src/store.js';import { planContactImport } from '../src/import-export.js';import { prepareCall, verifyPreparedCall, recoverCalls } from '../src/call-runner.js';import { preparedFixture, makeFixture, TEST_POLICY } from './fixtures/helpers.mjs';
function childAcquire(dbPath,callId){return new Promise((resolve)=>{const code=`import {VoiceStore} from ${JSON.stringify(new URL('../src/store.js',import.meta.url).href)};const s=new VoiceStore(${JSON.stringify(dbPath)});try{s.acquireStart(${JSON.stringify(callId)},{policy:${JSON.stringify(TEST_POLICY)},forReal:false});console.log('OK')}catch(e){console.log('BLOCK:'+e.message)}finally{s.close()}`;const p=spawn(process.execPath,['--input-type=module','-e',code],{env:{...process.env}});let out='';p.stdout.on('data',d=>out+=d);p.on('close',()=>resolve(out.trim()));});}

test('T05 trusted lookup uses contact id; raw/nonexistent phone does not become contact id',()=>{const f=makeFixture();try{assert.equal(f.store.getContact('+380501234567'),null);assert.throws(()=>prepareCall({store:f.store,config:f.config,policy:f.policy,contactId:'+380501234567',scenarioId:'initial_intro'}),/contact_not_found/);}finally{f.store.close()}});
test('T06 CSV cannot import approved/consent permission headers',()=>{const bad='contact_id,company_id,company_name,person_name,role_title,phone_e164,language_preference,company_context,contact_context,phone_source_ref,context_source_ref,approved\n,,Acme,A,CEO,+380501234567,uk,x,x,p,c,true\n';assert.throws(()=>planContactImport(bad),/header must be exactly/);});
test('T07 unapproved/revoked/expired/DNC and duplicate phone are blocked',()=>{
 const u=makeFixture({approve:false});try{assert.equal(u.store.gate(u.contactId,{policy:u.policy}).reason,'not_approved')}finally{u.store.close()}
 const r=makeFixture();try{const c=r.store.getContact(r.contactId);r.store.db.prepare('UPDATE authorizations SET revoked_at=? WHERE authorization_id=?').run('2026-10-09T00:00:00.000Z',c.authorization_id);assert.equal(r.store.gate(r.contactId,{policy:r.policy}).reason,'authorization_revoked')}finally{r.store.close()}
 const d=makeFixture();try{d.store.blockContact(d.contactId,{reason:'DNC',actor:{uid:1,user:'t'}});assert.equal(d.store.gate(d.contactId,{policy:d.policy}).reason,'phone_hold')}finally{d.store.close()}
 const x=makeFixture();try{const csv='contact_id,company_id,company_name,person_name,role_title,phone_e164,language_preference,company_context,contact_context,phone_source_ref,context_source_ref\n,,Other,B,CTO,+380501234567,uk,x,x,p,c\n';assert.throws(()=>x.store.addImportPlan(planContactImport(csv)),/Duplicate/)}finally{x.store.close()}
});
test('T08 prepared contact/company/policy/hash drift requires reprepare',()=>{const f=preparedFixture();try{verifyPreparedCall({store:f.store,config:f.config,policy:f.policy,callId:f.call.call_id,confirmPhone:f.call.target_e164,forReal:false});f.store.db.prepare('UPDATE contacts SET revision=revision+1,context=? WHERE contact_id=?').run('changed',f.contactId);assert.throws(()=>verifyPreparedCall({store:f.store,config:f.config,policy:f.policy,callId:f.call.call_id,confirmPhone:f.call.target_e164,forReal:false}),/drift|snapshot/);}finally{f.store.close()}});
test('T09 replayed start reservation never creates a second originate intent',()=>{const f=preparedFixture();try{const first=f.store.acquireStart(f.call.call_id,{policy:f.policy,forReal:false,expectedManifestHash:f.call.manifest_hash});assert.ok(first.originate_intent_at);assert.throws(()=>f.store.acquireStart(f.call.call_id,{policy:f.policy,forReal:false}),/already|expected prepared/i);assert.equal(f.store.db.prepare('SELECT COUNT(*) n FROM call_events WHERE call_id=? AND kind=?').get(f.call.call_id,'originate_intent').n,1);}finally{f.store.close()}});
test('T10 two separate processes starting different prepared calls get one global active slot',async()=>{const f=makeFixture();try{const a=prepareCall({store:f.store,config:f.config,policy:f.policy,contactId:f.contactId,scenarioId:'initial_intro',actor:{uid:1,user:'t'}});const b=prepareCall({store:f.store,config:f.config,policy:f.policy,contactId:f.contactId,scenarioId:'executive_intro',actor:{uid:1,user:'t'}});f.store.close();const [x,y]=await Promise.all([childAcquire(f.dbPath,a.call_id),childAcquire(f.dbPath,b.call_id)]);assert.equal([x,y].filter(v=>v==='OK').length,1,`${x} / ${y}`);}catch(e){try{f.store.close()}catch{}throw e}});
test('T11 prepared call with no intent is not auto-resumed by recovery',async()=>{const f=preparedFixture();try{assert.equal(f.store.pendingRecovery().length,0);const r=await recoverCalls({store:f.store,config:f.config,ariFactory:()=>{throw new Error('must not connect')}});assert.equal(r.recovered,0);assert.equal(f.store.getCall(f.call.call_id).state,'prepared');}finally{f.store.close()}});
test('T12 intent without confirmed POST response remains non-retriable and recoverable by saved ids',async()=>{const f=preparedFixture();try{f.store.acquireStart(f.call.call_id,{policy:f.policy,forReal:false});assert.throws(()=>f.store.acquireStart(f.call.call_id,{policy:f.policy,forReal:false}),/already|expected prepared/i);class A{async connect(){}async request(){return null}async exists(){return false}close(){}}const r=await recoverCalls({store:f.store,config:f.config,ariFactory:()=>new A(),isPidAlive:()=>false});assert.equal(r.recovered,1);assert.equal(f.store.getCall(f.call.call_id).state,'terminal');}finally{f.store.close()}});
test('T13 recovery never steals a live same-boot lock and only reconciles persisted resource ids after dead owner',async()=>{const f=preparedFixture();try{f.store.acquireStart(f.call.call_id,{policy:f.policy,forReal:false});let made=0;let r=await recoverCalls({store:f.store,config:f.config,ariFactory:()=>{made++;throw new Error('no')},isPidAlive:()=>true});assert.equal(r.skipped_live_lock,true);assert.equal(made,0);const touched=[];class A{async connect(){}async request(method,path){touched.push(path)}async exists(path){touched.push(path);return false}close(){}}r=await recoverCalls({store:f.store,config:f.config,ariFactory:()=>new A(),isPidAlive:()=>false});assert.equal(r.recovered,1);assert.ok(touched.every(p=>p.includes(f.call.phone_channel_id)||p.includes(f.call.media_channel_id)||p.includes(f.call.bridge_id)));}finally{f.store.close()}});
test('T34 every answered finalized call places a phone review hold; no-answer does not',()=>{const a=preparedFixture();try{a.store.acquireStart(a.call.call_id,{policy:a.policy,forReal:false});a.store.updateCall(a.call.call_id,{answeredAt:'2026-10-09T01:00:00.000Z'});a.store.finalizeCall(a.call.call_id,{cleanupState:{phone:'absent',media:'absent',bridge:'absent'},telephonyOutcome:'answered',terminationReason:'remote_hangup',transcriptEnvelope:{...a.call.transcript_envelope,state:'unavailable'},audioStats:a.call.audio_stats});assert.equal(a.store.getContact(a.contactId).review_pending,true);}finally{a.store.close()}});
test('T41 review CAS is atomic; clear_hold cannot clear confirmed DNC; explicit new approval can reopen with audit evidence',()=>{const f=preparedFixture();try{f.store.acquireStart(f.call.call_id,{policy:f.policy,forReal:false});f.store.updateCall(f.call.call_id,{answeredAt:'2026-10-09T01:00:00.000Z'});f.store.finalizeCall(f.call.call_id,{cleanupState:{phone:'absent',media:'absent',bridge:'absent'},telephonyOutcome:'answered',terminationReason:'remote_hangup',transcriptEnvelope:{...f.call.transcript_envelope,state:'unavailable'},audioStats:f.call.audio_stats});f.store.blockContact(f.contactId,{reason:'confirmed DNC',actor:{uid:1,user:'t'}});const c=f.store.getContact(f.contactId), base={review_id:randomUUID(),call_id:f.call.call_id,result_id:null,expected_contact_revision:c.revision,actor:{uid:1,user:'t'},reviewed_at:'2026-10-09T02:00:00.000Z',decision:'inconclusive',dnc_action:'clear_hold',corrected_semantic:null,accepted_next_action:null,contact_updates:{person_name:null,role_title:null,phone_e164:null},notes:'reviewed',evidence_event_ids:[]};f.store.applyReview(base);assert.equal(f.store.getContact(f.contactId).dnc_state,'confirmed');f.store.db.prepare('UPDATE contacts SET revision=revision+1 WHERE contact_id=?').run(f.contactId);assert.throws(()=>f.store.applyReview({...base,review_id:randomUUID()}),/CAS conflict/);f.store.approveContact(f.contactId,{basis:'test_authorized',evidenceRef:'new-review-evidence',policyVersion:'test-policy-v2',actor:{uid:1,user:'owner'}});assert.equal(f.store.getContact(f.contactId).dnc_state,'clear');}finally{f.store.close()}});
test('T46 migrations are repeatable across reopen, closed backup restores, WAL/pragmas and secure DB mode remain active',()=>{const f=makeFixture();const p=f.dbPath;f.store.close();assert.equal(statSync(p).mode&0o777,0o600);const backup=p+'.backup';copyFileSync(p,backup);const a=new VoiceStore(p);const v=a.db.prepare('SELECT version FROM schema_meta').all();assert.deepEqual(v.map(x=>x.version),[1]);assert.equal(a.db.prepare('PRAGMA foreign_keys').get().foreign_keys,1);assert.equal(a.db.prepare('PRAGMA synchronous').get().synchronous,2);const jm=a.db.prepare('PRAGMA journal_mode').get().journal_mode;assert.equal(jm,'wal');a.close();const b=new VoiceStore(p);assert.equal(b.listContacts().length,1);b.close();const restored=new VoiceStore(backup);assert.equal(restored.listContacts().length,1);assert.equal(restored.pendingRecovery().length,0);assert.equal(statSync(backup).mode&0o777,0o600);restored.close();});
