import test from 'node:test';import assert from 'node:assert/strict';
import { TranscriptCollector, stopGuardWindow } from '../src/transcript.js';
function add(c,o){return c.add({sessionId:'s1',eventId:o.id,speaker:o.speaker,startMs:o.start,endMs:o.end,delta:o.delta,phase:o.phase||'active',receivedAt:'2026-10-09T00:00:00.000Z'});}
test('T28 interleaved transcript preserves exact whitespace/repeated words and dedups event id',()=>{const c=new TranscriptCollector('00000000-0000-4000-8000-000000000001');add(c,{id:'u1',speaker:'user',start:100,end:200,delta:'так так '});add(c,{id:'a1',speaker:'assistant',start:150,end:220,delta:'Добре'});add(c,{id:'u2',speaker:'user',start:200,end:300,delta:'саме так'});assert.equal(c.textFor('user'),'так так саме так');assert.equal(c.textFor('assistant'),'Добре');assert.equal(add(c,{id:'u2',speaker:'user',start:300,end:400,delta:'X'}).reason,'duplicate');assert.deepEqual(c.displayTimeline().map(x=>x.event_id),['u1','a1','u2']);});
test('T29 valid overlap accepted; negative/invalid/oversize event makes controlled partial stop',()=>{const c=new TranscriptCollector('00000000-0000-4000-8000-000000000001',{maxFragmentBytes:5});assert.equal(add(c,{id:'u1',speaker:'user',start:10,end:20,delta:'abc'}).accepted,true);assert.equal(add(c,{id:'a1',speaker:'assistant',start:15,end:25,delta:'def'}).accepted,true);const bad=add(c,{id:'u2',speaker:'user',start:-1,end:4,delta:'x'});assert.equal(bad.stop,true);assert.equal(c.freeze().state,'partial');});
test('T29 segment and total-byte bounds stop instead of unbounded capture',()=>{const c=new TranscriptCollector('00000000-0000-4000-8000-000000000001',{maxSegments:1,maxTextBytes:4});assert.ok(add(c,{id:'1',speaker:'user',start:0,end:1,delta:'abcd'}).accepted);assert.equal(add(c,{id:'2',speaker:'user',start:1,end:2,delta:'x'}).reason,'size_limit');});
test('T30 drain trailing captions are retained, audio delivery remains unknown, hash freezes',()=>{const c=new TranscriptCollector('00000000-0000-4000-8000-000000000001');add(c,{id:'a1',speaker:'assistant',start:1,end:2,delta:'tail',phase:'draining'});const e=c.freeze();assert.equal(c.segments[0].delivery,'after_stop_unknown');assert.ok(e.issues.includes('output_delivery_uncertain'));assert.match(e.sha256,/^[0-9a-f]{64}$/);assert.equal(add(c,{id:'u2',speaker:'user',start:3,end:4,delta:'late'}).reason,'frozen');});
test('T31 empty answered transcript is unavailable; no-answer is not_applicable',()=>{const id='00000000-0000-4000-8000-000000000001';assert.equal(new TranscriptCollector(id).freeze({unavailable:true}).state,'unavailable');assert.equal(new TranscriptCollector(id).freeze({notApplicable:true}).state,'not_applicable');});
test('T32 fragmented Ukrainian/Russian DNC and rejection trigger user-only guard',()=>{const c=new TranscriptCollector('00000000-0000-4000-8000-000000000001');assert.equal(add(c,{id:'1',speaker:'user',start:0,end:1,delta:'більше не дзво'}).guard,null);assert.equal(add(c,{id:'2',speaker:'user',start:1,end:2,delta:'ніть'}).guard.type,'dnc');assert.equal(stopGuardWindow('не звоните мне пожалуйста'),'dnc');assert.equal(stopGuardWindow('мені не цікаво, не цікавить'),'rejection');});
test('T33 quoted/negated DNC, standalone no and price objection do not naively stop',()=>{for(const x of ['ні','нет','дорого, какая цена?','Я не казав не звоните мне','Якщо клієнт каже «не телефонуйте мені», що далі?'])assert.equal(stopGuardWindow(x),null,x);});
