import dgram from 'node:dgram';
import { isIP } from 'node:net';
import { networkInterfaces } from 'node:os';
import { AriClient, waitForAriEvent } from './ari.js';
import { OpenAILive } from './openai-live.js';
import { parseRtp, RtpPacketizer } from './rtp.js';
import { AudioQueue, AudioPacer } from './audio-queue.js';
import { safeMessage } from './config.js';
import { buildDialRoute } from './telephony-route.js';
import { classifyUnanswered } from './call-lifecycle.js';
import { TranscriptCollector } from './transcript.js';

function nowIso(){return new Date().toISOString()}
export class CallSession {
  constructor(config, call, dependencies={}) {
    this.config=config; this.call=call; this.number=call.target_e164; this.app=call.ari_app; this.phoneId=call.phone_channel_id;this.externalId=call.media_channel_id;this.bridgeId=call.bridge_id;
    this.ari=dependencies.ari||new AriClient(config,this.app);this.live=dependencies.live||new OpenAILive({...config,instructions:call.prompt_snapshot.instructions,inputDataJson:call.prompt_snapshot.input_data_json});this.udp=dependencies.udp||dgram.createSocket('udp4');this.log=dependencies.log||console.log;this.warn=dependencies.warn||console.error;this.onFact=dependencies.onFact||(()=>{});this.persistSegment=dependencies.persistSegment||(()=>{});this.onProtectiveStop=dependencies.onProtectiveStop||(()=>{});this.beforeOriginate=dependencies.beforeOriginate||(()=>{});this.afterOriginate=dependencies.afterOriginate||(()=>{});this.now=dependencies.now||nowIso;this.timers=dependencies.timers||{setTimeout,clearTimeout};
    this.abort=new AbortController();this.queue=new AudioQueue(config.maxQueueFrames);this.packetizer=new RtpPacketizer({payloadType:0});this.pacer=new AudioPacer(this.queue,(f)=>this.sendFrame(f),(e)=>this.cleanup('media_error',e));
    this.closing=false;this.mediaActive=false;this.failed=false;this.answered=false;this.dialstatus=null;this.ariCause=null;this.terminationReason='unknown';this.collector=new TranscriptCollector(call.call_id);
    this.stats={input_packets:0,input_bytes:0,output_packets:0,output_non_silence_bytes:0,pre_media_dropped_bytes:0,queued_bytes_at_stop:0,invalid_packets:0,foreign_packets:0,stale_packets:0};this.cleanupState={phone:'absent',media:'absent',bridge:'absent'};
    this.done=new Promise(r=>{this.resolveDone=r});
    this.ari.on('fault',(e)=>this.cleanup('ari_error',e));this.live.on('fault',(e)=>this.cleanup('openai_error',e));this.ari.on('event',(e)=>this.handleAriEvent(e));
    this.live.on('sessionStarted',({sessionId})=>{this.sessionId=sessionId;this.onFact({kind:'live_started',sessionId,at:this.now()})});this.live.on('usage',(seconds)=>this.onFact({kind:'live_usage',seconds,at:this.now()}));
    this.live.on('transcript',(e)=>this.handleTranscript(e));this.live.on('transcriptInvalid',()=>{this.collector.markIssue('invalid_event');void this.cleanup('media_error',new Error('Invalid Live transcript event.'))});
    this.live.on('delegationLimit',()=>void this.cleanup('policy_stop',new Error('Delegation fallback limit exceeded.')));
    this.live.on('audio',(bytes)=>{if(!this.mediaActive||this.closing){this.stats.pre_media_dropped_bytes+=bytes.length;return;}try{this.pacer.push(bytes)}catch(e){void this.cleanup('media_error',e)}});
    this.udp.on('message',(p,r)=>this.receiveRtp(p,r));this.udp.on('error',()=>void this.cleanup('media_error',new Error('Local RTP/UDP socket failed.')));
  }
  assertActive(){if(this.closing)throw new Error('Call ending.');}
  async run(){if(this.startTask)throw new Error('CallSession only supports one run.');this.startedMs=Date.now();this.totalTimer=this.timers.setTimeout(()=>void this.cleanup('max_duration'),this.config.maxTotalSeconds*1000);this.startupTimer=this.timers.setTimeout(()=>void this.cleanup('startup_timeout'),this.config.startupTimeoutSeconds*1000);this.startTask=this.start();try{await this.startTask}catch(e){if(!this.closing){const reason=this.answered?'media_error':/Timed out waiting for ARI event/.test(String(e?.message))?'no_answer_timeout':'ari_error';void this.cleanup(reason,e)}}return this.done}
  async bindUdp(){await Promise.race([new Promise((resolve,reject)=>{const err=()=>{this.udp.off('listening',ok);reject(new Error('UDP bind failed.'))};const ok=()=>{this.udp.off('error',err);this.udpBound=true;resolve()};this.udp.once('error',err);this.udp.once('listening',ok);this.udp.bind(0,this.config.bindAddress)}),new Promise((_,reject)=>this.timers.setTimeout(()=>reject(new Error('UDP bind timeout.')),this.config.requestTimeoutMs))])}
  async start(){
    await this.ari.connect();this.assertActive();await this.live.connect();this.assertActive();await this.bindUdp();this.assertActive();
    const route=buildDialRoute(this.number,{endpointAlias:this.call.config_snapshot.endpoint_alias,dialNumberFormat:this.call.config_snapshot.dial_number_format,outboundCallerId:this.call.config_snapshot.outbound_caller_id});
    const phoneReady=waitForAriEvent(this.ari,e=>e.type==='StasisStart'&&e.channel?.id===this.phoneId,(this.config.answerTimeoutSeconds+10)*1000,this.abort.signal);phoneReady.catch(()=>{});
    this.phoneAttempted=true;this.cleanupState.phone='pending';this.beforeOriginate();
    await this.ari.request('POST','/channels',{endpoint:route.endpoint,app:this.app,channelId:this.phoneId,timeout:this.config.answerTimeoutSeconds,formats:'ulaw',callerId:route.callerId},{variables:{'TIMEOUT(absolute)':String(this.config.asteriskAbsoluteSeconds)}});this.afterOriginate();this.assertActive();
    const answered=await phoneReady;this.assertActive();if(answered.channel?.state!=='Up')throw new Error('Phone channel not Up.');this.answered=true;this.answeredAt=this.now();this.onFact({kind:'answered',at:this.answeredAt});this.talkTimer=this.timers.setTimeout(()=>void this.cleanup('max_duration'),this.config.maxTalkSeconds*1000);
    this.bridgeAttempted=true;this.cleanupState.bridge='pending';await this.ari.request('POST',`/bridges/${this.bridgeId}`,{type:'mixing,proxy_media'});this.assertActive();await this.ari.request('POST',`/bridges/${this.bridgeId}/addChannel`,{channel:this.phoneId});this.assertActive();
    const mediaReady=waitForAriEvent(this.ari,e=>e.type==='StasisStart'&&e.channel?.id===this.externalId,this.config.requestTimeoutMs+5000,this.abort.signal);mediaReady.catch(()=>{});this.externalAttempted=true;this.cleanupState.media='pending';
    await this.ari.request('POST','/channels/externalMedia',{app:this.app,channelId:this.externalId,external_host:`${this.config.bindAddress}:${this.udp.address().port}`,transport:'udp',encapsulation:'rtp',connection_type:'client',format:'ulaw',direction:'both'});this.assertActive();await mediaReady;this.assertActive();
    const address=await this.ari.request('GET',`/channels/${this.externalId}/variable`,{variable:'UNICASTRTP_LOCAL_ADDRESS'});const port=await this.ari.request('GET',`/channels/${this.externalId}/variable`,{variable:'UNICASTRTP_LOCAL_PORT'});this.assertActive();const host=address?.value,portNumber=Number(port?.value);let local=isIP(host||'')===4&&host.startsWith('127.');if(!local&&isIP(host||'')===4){try{local=Object.values(networkInterfaces()).flat().filter(Boolean).some(x=>x.address===host)}catch{throw new Error('STOP/HOLD: cannot prove ExternalMedia locality.')}}if(isIP(host||'')!==4||!local||!Number.isInteger(portNumber)||portNumber<1||portNumber>65535)throw new Error('STOP/HOLD: invalid/non-local ExternalMedia address.');
    this.mediaEndpoint={host,port:portNumber};await this.ari.request('POST',`/bridges/${this.bridgeId}/addChannel`,{channel:this.externalId});this.assertActive();this.mediaActive=true;this.mediaReadyAt=this.now();this.onFact({kind:'media_ready',at:this.mediaReadyAt});this.timers.clearTimeout(this.startupTimer);this.pacer.start();this.live.greet(this.call.prompt_snapshot.greeting);this.armMediaTimeout();
  }
  armMediaTimeout(){this.timers.clearTimeout(this.mediaTimer);this.mediaTimer=this.timers.setTimeout(()=>void this.cleanup('media_error',new Error('media_transport_timeout')),this.config.mediaTransportTimeoutSeconds*1000)}
  handleTranscript(e){const phase=!this.mediaReadyAt?'pre_media':this.closing?'draining':'active';const out=this.collector.add({sessionId:this.sessionId||'pending-session',eventId:e.eventId,speaker:e.speaker,startMs:e.startMs,endMs:e.endMs,delta:e.delta,phase,receivedAt:this.now()});if(!out.accepted){if(out.stop)void this.cleanup('persistence_error',new Error(out.reason));return}try{this.persistSegment(out.segment)}catch(err){this.collector.markIssue('persistence_error');void this.cleanup('persistence_error',err);return}if(out.guard?.type==='dnc'){this.onProtectiveStop({type:'dnc',phone:this.number,evidenceEventId:out.guard.evidenceEventId});void this.cleanup('policy_stop')}else if(out.guard?.type==='rejection'){this.onProtectiveStop({type:'rejection',phone:this.number,evidenceEventId:out.guard.evidenceEventId});void this.cleanup('policy_stop')}}
  handleAriEvent(event){
    const id=event.channel?.id||event.peer?.id;if(id!==this.phoneId&&id!==this.externalId&&event.peer?.id!==this.phoneId)return;
    if(event.type==='Dial'){if(event.dialstatus)this.dialstatus=event.dialstatus;return}
    if(event.type==='ChannelDestroyed'&&id===this.phoneId){if(Number.isInteger(event.cause))this.ariCause=event.cause;this.onFact({kind:'late_cause',cause:this.ariCause,at:this.now()});if(!this.closing)void this.cleanup(this.answered?'remote_hangup':'carrier_end');return}
    if(event.type==='StasisEnd'){if(id===this.externalId&&!this.closing)void this.cleanup('media_error',new Error('ExternalMedia ended.'));else if(id===this.phoneId&&!this.closing)void this.cleanup(this.answered?'remote_hangup':'carrier_end');}
  }
  receiveRtp(packet,remote){if(!this.mediaActive||this.closing)return;if(remote.address!==this.mediaEndpoint.host||remote.port!==this.mediaEndpoint.port){this.stats.foreign_packets++;return}const parsed=parseRtp(packet,[this.config.payloadType]);if(!parsed){this.stats.invalid_packets++;return}if(this.inputSsrc===parsed.ssrc&&this.inputSequence!==undefined){const f=(parsed.sequence-this.inputSequence)&0xffff;if(!f||f>=0x8000){this.stats.stale_packets++;return}}this.inputSsrc=parsed.ssrc;this.inputSequence=parsed.sequence;this.armMediaTimeout();try{this.live.appendAudio(parsed.payload);this.stats.input_packets++;this.stats.input_bytes+=parsed.payload.length}catch(e){void this.cleanup('openai_error',e)}}
  sendFrame(frame){if(!this.mediaActive||this.closing)return;this.udp.send(this.packetizer.next(frame),this.mediaEndpoint.port,this.mediaEndpoint.host,(e)=>{if(e&&!this.closing)void this.cleanup('media_error',new Error('RTP send failed.'))});this.stats.output_packets++;if(!frame.equals(Buffer.alloc(frame.length,0xff)))this.stats.output_non_silence_bytes+=frame.length}
  cleanup(reason='operator_stop',error){if(this.cleanupPromise)return this.cleanupPromise;this.closing=true;this.mediaActive=false;this.terminationReason=reason;this.abort.abort();this.timers.clearTimeout(this.totalTimer);this.timers.clearTimeout(this.startupTimer);this.timers.clearTimeout(this.talkTimer);this.timers.clearTimeout(this.mediaTimer);this.stats.queued_bytes_at_stop=this.queue.bytes;this.pacer.stop();if(error){this.failed=true;this.warn(`${reason}: ${safeMessage(error,this.config)}`)}this.cleanupPromise=Promise.resolve().then(()=>this.finishCleanup());return this.cleanupPromise}
  async verifyDelete(path,key){try{await this.ari.request('DELETE',path,{}, {ignoreMissing:true});const exists=await this.ari.exists(path);this.cleanupState[key]=exists?'unknown':'absent'}catch{this.cleanupState[key]='unknown';this.failed=true}}
  async finishCleanup(){try{await this.startTask?.catch(()=>{});if(this.phoneAttempted)await this.verifyDelete(`/channels/${this.phoneId}`,'phone');const liveResult=await this.live.close().catch(()=>({confirmed:false}));if(!liveResult?.confirmed)this.collector.markIssue('finalization_unconfirmed');if(this.externalAttempted)await this.verifyDelete(`/channels/${this.externalId}`,'media');if(this.bridgeAttempted)await this.verifyDelete(`/bridges/${this.bridgeId}`,'bridge');if(this.udpBound)await new Promise(r=>{try{this.udp.close(r)}catch{r()}});this.ari.close();const envelope=this.collector.freeze({notApplicable:!this.answered,unavailable:this.answered&&!this.collector.segments.length});const outcome=this.answered?'answered':this.terminationReason==='no_answer_timeout'?'no_answer':classifyUnanswered({dialstatus:this.dialstatus,cause:this.ariCause}).telephonyOutcome;const result={failed:this.failed,telephonyOutcome:outcome,terminationReason:this.terminationReason,cleanupState:{...this.cleanupState},transcriptEnvelope:envelope,audioStats:{...this.stats},openaiFinalization:liveResult?.confirmed?'confirmed':'unconfirmed',latestUsageSeconds:this.live.latestUsageSeconds??null,finalUsageSeconds:this.live.finalUsageSeconds??null,answeredAt:this.answeredAt||null,mediaReadyAt:this.mediaReadyAt||null,ariCause:this.ariCause,dialstatus:this.dialstatus};this.resolveDone(result);return result}finally{}}
}
