import { DatabaseSync } from 'node:sqlite';
import { chmodSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { validateE164 } from './telephony-route.js';
const here=dirname(fileURLToPath(import.meta.url));
const migration=readFileSync(resolve(here,'../migrations/001_pilot.sql'),'utf8');
const iso=()=>new Date().toISOString();
function j(x){return JSON.stringify(x)}
function p(x,fallback=null){try{return x==null?fallback:JSON.parse(x)}catch{return fallback}}
function bootId(){try{return readFileSync('/proc/sys/kernel/random/boot_id','utf8').trim()}catch{return 'unknown-boot'}}
export function assertSqliteCapability(){ if(typeof DatabaseSync!=='function') throw new Error('HOLD: node:sqlite DatabaseSync unavailable; Node >=22.13.0 required.'); return true; }

export class VoiceStore {
  constructor(path,{now=iso,pid=process.pid,boot=bootId()}={}){
    assertSqliteCapability(); this.path=path; this.now=now; this.pid=pid; this.bootId=boot;
    mkdirSync(dirname(path),{recursive:true,mode:0o700}); this.db=new DatabaseSync(path); chmodSync(path,0o600);
    this.db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000;');
    this.db.exec(migration); this.db.prepare('INSERT OR IGNORE INTO schema_meta(version,applied_at) VALUES(1,?)').run(this.now());
  }
  close(){this.db.close()}
  tx(fn){this.db.exec('BEGIN IMMEDIATE'); try{const r=fn(); this.db.exec('COMMIT'); return r}catch(e){try{this.db.exec('ROLLBACK')}catch{} throw e}}
  addImportPlan(plan){ return this.tx(()=>{
    for(const c of plan.companies){ const existing=this.db.prepare('SELECT * FROM companies WHERE company_id=?').get(c.company_id); if(existing){ if(existing.name!==c.name||existing.context!==c.context) throw new Error(`Company conflict: ${c.company_id}`); continue; }
      this.db.prepare('INSERT INTO companies(company_id,revision,name,context,source_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(c.company_id,1,c.name,c.context,j(c.source),c.created_at,c.updated_at);
    }
    for(const c of plan.contacts){
      if(this.db.prepare('SELECT 1 FROM contacts WHERE contact_id=? OR phone_e164=?').get(c.contact_id,c.phone_e164)) throw new Error(`Duplicate contact id/phone: ${c.contact_id}`);
      this.db.prepare(`INSERT INTO contacts(contact_id,revision,company_id,person_name,role_title,phone_e164,language_preference,context,phone_source_json,context_source_json,permission_state,authorization_id,dnc_state,dnc_reason,last_call_id,last_attempt_at,next_action_json,review_pending,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`)
        .run(c.contact_id,1,c.company_id,c.person_name,c.role_title,c.phone_e164,c.language_preference,c.context,j(c.phone_source),j(c.context_source),'unreviewed',null,'clear',null,null,null,null,0,c.created_at,c.updated_at);
    }
    return {companies:plan.companies.length,contacts:plan.contacts.length};
  })}
  listContacts(){return this.db.prepare('SELECT contact_id,company_id,person_name,role_title,phone_e164,language_preference,permission_state,dnc_state,review_pending,revision FROM contacts ORDER BY created_at,contact_id').all()}
  getCompany(id){const r=this.db.prepare('SELECT * FROM companies WHERE company_id=?').get(id); return r?{company_id:r.company_id,revision:r.revision,name:r.name,context:r.context,source:p(r.source_json,{}),created_at:r.created_at,updated_at:r.updated_at}:null}
  getContact(id){const r=this.db.prepare('SELECT * FROM contacts WHERE contact_id=?').get(id); if(!r)return null; return {contact_id:r.contact_id,revision:r.revision,company_id:r.company_id,person_name:r.person_name,role_title:r.role_title,phone_e164:r.phone_e164,language_preference:r.language_preference,context:r.context,phone_source:p(r.phone_source_json,{}),context_source:p(r.context_source_json,{}),permission_state:r.permission_state,authorization_id:r.authorization_id,dnc_state:r.dnc_state,last_call_id:r.last_call_id,last_attempt_at:r.last_attempt_at,next_action:p(r.next_action_json),review_pending:!!r.review_pending,created_at:r.created_at,updated_at:r.updated_at}}
  showContact(id){const contact=this.getContact(id); if(!contact)throw new Error(`Contact not found: ${id}`); return {contact,company:this.getCompany(contact.company_id),authorization:contact.authorization_id?this.getAuthorization(contact.authorization_id):null}}
  getAuthorization(id){const r=this.db.prepare('SELECT * FROM authorizations WHERE authorization_id=?').get(id); if(!r)return null; return {...r,actor:p(r.actor_json,{})}}
  approveContact(contactId,{basis,evidenceRef,policyVersion,actor,expiresAt=null,reason='operator authorization'}){ if(!/^[a-z][a-z0-9_.:-]{2,63}$/.test(basis||''))throw new Error('Invalid authorization basis id.'); if(!evidenceRef||!policyVersion)throw new Error('Evidence and policy are required.'); return this.tx(()=>{
    const c=this.db.prepare('SELECT c.*,co.revision company_revision FROM contacts c JOIN companies co ON co.company_id=c.company_id WHERE c.contact_id=?').get(contactId); if(!c)throw new Error('Contact not found.');
    const rev=c.revision+1,id=randomUUID(),at=this.now();
    this.db.prepare("UPDATE contacts SET revision=?,permission_state='approved',authorization_id=?,dnc_state='clear',dnc_reason=NULL,review_pending=0,updated_at=? WHERE contact_id=?").run(rev,id,at,contactId);
    this.db.prepare(`INSERT INTO authorizations(authorization_id,contact_id,phone_e164,contact_revision,company_revision,policy_version,basis,evidence_ref,authorized_at,expires_at,actor_json,revoked_at,reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,contactId,c.phone_e164,rev,c.company_revision,policyVersion,basis,evidenceRef,at,expiresAt,j(actor),null,reason);
    return this.getAuthorization(id);
  })}
  blockContact(contactId,{reason,actor}){return this.tx(()=>{const c=this.db.prepare('SELECT * FROM contacts WHERE contact_id=?').get(contactId);if(!c)throw new Error('Contact not found.');const at=this.now(); this.db.prepare("UPDATE contacts SET revision=revision+1,permission_state='blocked',dnc_state='confirmed',dnc_reason=?,authorization_id=NULL,updated_at=? WHERE phone_e164=?").run(reason||'operator block',at,c.phone_e164); this.db.prepare("UPDATE authorizations SET revoked_at=COALESCE(revoked_at,?) WHERE phone_e164=?").run(at,c.phone_e164); return {phone_e164:c.phone_e164,actor,blocked_at:at}})}
  setProtectiveHoldByPhone(phone,reason){validateE164(phone);return this.tx(()=>{const at=this.now();this.db.prepare("UPDATE contacts SET dnc_state=CASE WHEN dnc_state='confirmed' THEN 'confirmed' ELSE 'hold' END,dnc_reason=?,updated_at=? WHERE phone_e164=?").run(reason,at,phone);return true})}
  gate(contactId,{policy,forReal=false}={}){const c=this.db.prepare('SELECT c.*,co.revision company_revision FROM contacts c JOIN companies co ON co.company_id=c.company_id WHERE c.contact_id=?').get(contactId); if(!c)return {allowed:false,reason:'contact_not_found'};
    const anyHold=this.db.prepare("SELECT dnc_state,review_pending FROM contacts WHERE phone_e164=? AND (dnc_state IN ('hold','confirmed') OR review_pending=1) LIMIT 1").get(c.phone_e164); if(anyHold)return {allowed:false,reason:anyHold.review_pending?'review_pending':'phone_hold'};
    if(c.permission_state!=='approved'||!c.authorization_id)return {allowed:false,reason:'not_approved'}; const a=this.db.prepare('SELECT * FROM authorizations WHERE authorization_id=?').get(c.authorization_id); if(!a||a.revoked_at)return {allowed:false,reason:'authorization_revoked'}; const now=this.now(); if(a.expires_at&&a.expires_at<=now)return {allowed:false,reason:'authorization_expired'}; if(a.phone_e164!==c.phone_e164||a.contact_revision!==c.revision||a.company_revision!==c.company_revision)return {allowed:false,reason:'authorization_snapshot_mismatch'};
    const allowed=forReal?(policy?.allowed_authorization_basis_ids||[]):(policy?.test_authorization_basis_ids||[]); if(!allowed.includes(a.basis))return {allowed:false,reason:'authorization_basis_not_enabled'};
    return {allowed:true,contact:this.getContact(contactId),company:this.getCompany(c.company_id),authorization:this.getAuthorization(c.authorization_id)} }
  createCall(call){this.db.prepare(`INSERT INTO calls(call_id,contact_id,company_id,authorization_id,actor_json,contact_revision,company_revision,target_e164,prepared_at,expires_at,manifest_hash,prompt_snapshot_json,config_snapshot_json,context_snapshot_json,state,started_at,originate_intent_at,originate_dispatched_at,answered_at,media_ready_at,end_observed_at,finalized_at,ari_app,phone_channel_id,media_channel_id,bridge_id,openai_session_id,telephony_outcome,termination_reason,ari_cause,dialstatus,talk_duration_ms,total_duration_ms,processing_status,cleanup_state_json,openai_finalization,latest_usage_seconds,final_usage_seconds,transcript_state,transcript_envelope_json,audio_stats_json,review_required,start_error_code,scenario_id,scenario_version,scenario_variant_label,scenario_hash) VALUES(${Array(47).fill('?').join(',')})`).run(
    call.call_id,call.contact_id,call.company_id,call.authorization_id,j(call.actor),call.contact_revision,call.company_revision,call.target_e164,call.prepared_at,call.expires_at,call.manifest_hash,j(call.prompt_snapshot),j(call.config_snapshot),j(call.context_snapshot),call.state,call.started_at,call.originate_intent_at,null,call.answered_at,call.media_ready_at,call.end_observed_at,call.finalized_at,call.ari_app,call.phone_channel_id,call.media_channel_id,call.bridge_id,call.openai_session_id,call.telephony_outcome,call.termination_reason,call.ari_cause,call.dialstatus,call.talk_duration_ms,call.total_duration_ms,call.processing_status,j(call.cleanup_state),call.openai_finalization,call.latest_usage_seconds,call.final_usage_seconds,call.transcript_state,j(call.transcript_envelope),j(call.audio_stats),call.review_required?1:0,null,call.prompt_snapshot.scenario_id,call.prompt_snapshot.scenario_version,call.prompt_snapshot.variant_label,call.prompt_snapshot.sha256); return call}
  rowCall(r){if(!r)return null; return {...r,actor:p(r.actor_json,{}),prompt_snapshot:p(r.prompt_snapshot_json,{}),config_snapshot:p(r.config_snapshot_json,{}),context_snapshot:p(r.context_snapshot_json,{}),cleanup_state:p(r.cleanup_state_json,{}),transcript_envelope:p(r.transcript_envelope_json,{}),audio_stats:p(r.audio_stats_json,{}),review_required:!!r.review_required}}
  getCall(id){return this.rowCall(this.db.prepare('SELECT * FROM calls WHERE call_id=?').get(id))}
  addEvent(callId,kind,{source='app',sourceEventId=null,channelId=null,cause=null,dialstatus=null,errorCode=null}={}){const seq=(this.db.prepare('SELECT COALESCE(MAX(seq),0)+1 n FROM call_events WHERE call_id=?').get(callId).n); this.db.prepare('INSERT INTO call_events(call_id,seq,kind,observed_at,source,source_event_id,channel_id,cause,dialstatus,error_code) VALUES(?,?,?,?,?,?,?,?,?,?)').run(callId,seq,kind,this.now(),source,sourceEventId,channelId,cause,dialstatus,errorCode); return seq}
  acquireStart(callId,{policy,forReal=false,expectedManifestHash=null}={}){return this.tx(()=>{
    const call=this.db.prepare('SELECT * FROM calls WHERE call_id=?').get(callId);if(!call)throw new Error('Call not found.');
    if(call.originate_intent_at)throw Object.assign(new Error('Start already reserved; automatic redial forbidden.'),{code:'already_started'});
    if(call.state!=='prepared')throw new Error(`Call state is ${call.state}, expected prepared.`);
    if(call.expires_at<=this.now())throw new Error('Prepared call expired; reprepare required.');
    if(expectedManifestHash&&call.manifest_hash!==expectedManifestHash)throw Object.assign(new Error('Prepared manifest changed.'),{code:'prepared_manifest_drift'});
    const c=this.db.prepare('SELECT c.*,co.revision company_revision FROM contacts c JOIN companies co ON co.company_id=c.company_id WHERE c.contact_id=?').get(call.contact_id);
    const held=this.db.prepare("SELECT dnc_state,review_pending FROM contacts WHERE phone_e164=? AND (dnc_state IN ('hold','confirmed') OR review_pending=1) LIMIT 1").get(call.target_e164);
    if(held)throw Object.assign(new Error('Phone hold/review blocks start.'),{code:held.review_pending?'review_pending':'phone_hold'});
    if(!c||c.revision!==call.contact_revision||c.company_revision!==call.company_revision||c.phone_e164!==call.target_e164||c.authorization_id!==call.authorization_id||c.permission_state!=='approved')throw Object.assign(new Error('Prepared contact snapshot drifted.'),{code:'prepared_snapshot_drift'});
    const a=this.db.prepare('SELECT * FROM authorizations WHERE authorization_id=?').get(call.authorization_id);
    if(!a||a.revoked_at||(a.expires_at&&a.expires_at<=this.now())||a.phone_e164!==call.target_e164||a.contact_revision!==c.revision||a.company_revision!==c.company_revision)throw Object.assign(new Error('Authorization is no longer current.'),{code:'authorization_snapshot_mismatch'});
    const allowed=forReal?(policy?.allowed_authorization_basis_ids||[]):(policy?.test_authorization_basis_ids||[]);if(!allowed.includes(a.basis))throw Object.assign(new Error('Authorization basis is not enabled by policy.'),{code:'authorization_basis_not_enabled'});
    const bad=this.db.prepare("SELECT call_id FROM calls WHERE call_id<>? AND ((state IN ('starting','dialing','answered','ending')) OR (state='terminal' AND (json_extract(cleanup_state_json,'$.phone')<>'absent' OR json_extract(cleanup_state_json,'$.media')<>'absent' OR json_extract(cleanup_state_json,'$.bridge')<>'absent'))) LIMIT 1").get(callId);
    if(bad)throw new Error(`Another active/unreconciled call blocks start: ${bad.call_id}`);
    const lock=this.db.prepare("SELECT * FROM runtime_lock WHERE scope='voice_pilot'").get();if(lock)throw new Error(`Global voice lock held by call ${lock.call_id}.`);
    const at=this.now();this.db.prepare("INSERT INTO runtime_lock(scope,call_id,pid,boot_id,acquired_at,heartbeat_at) VALUES('voice_pilot',?,?,?,?,?)").run(callId,this.pid,this.bootId,at,at);
    const changed=this.db.prepare("UPDATE calls SET state='starting',started_at=?,originate_intent_at=? WHERE call_id=? AND state='prepared' AND originate_intent_at IS NULL").run(at,at,callId);if(changed.changes!==1)throw new Error('Start CAS failed.');
    this.addEvent(callId,'start_reserved');this.addEvent(callId,'originate_intent');return this.getCall(callId)
  })}
  markOriginateDispatched(id){const at=this.now();this.db.prepare("UPDATE calls SET originate_dispatched_at=?,state=CASE WHEN state='starting' THEN 'dialing' ELSE state END WHERE call_id=? AND originate_dispatched_at IS NULL").run(at,id);this.addEvent(id,'originate_response',{source:'ari'})}
  updateCall(id,fields){const allowed={state:'state',answeredAt:'answered_at',mediaReadyAt:'media_ready_at',endObservedAt:'end_observed_at',finalizedAt:'finalized_at',openaiSessionId:'openai_session_id',telephonyOutcome:'telephony_outcome',terminationReason:'termination_reason',ariCause:'ari_cause',dialstatus:'dialstatus',talkDurationMs:'talk_duration_ms',totalDurationMs:'total_duration_ms',processingStatus:'processing_status',cleanupState:'cleanup_state_json',openaiFinalization:'openai_finalization',latestUsageSeconds:'latest_usage_seconds',finalUsageSeconds:'final_usage_seconds',transcriptState:'transcript_state',transcriptEnvelope:'transcript_envelope_json',audioStats:'audio_stats_json',reviewRequired:'review_required',startErrorCode:'start_error_code'}; const sets=[],vals=[];for(const[k,v]of Object.entries(fields)){if(!allowed[k])throw new Error(`Unsupported call field ${k}`);sets.push(`${allowed[k]}=?`);vals.push(['cleanupState','transcriptEnvelope','audioStats'].includes(k)?j(v):k==='reviewRequired'?(v?1:0):v)} if(!sets.length)return; this.db.prepare(`UPDATE calls SET ${sets.join(',')} WHERE call_id=?`).run(...vals,id)}
  releaseLock(id){this.db.prepare("DELETE FROM runtime_lock WHERE scope='voice_pilot' AND call_id=?").run(id)}
  getRuntimeLock(){return this.db.prepare("SELECT * FROM runtime_lock WHERE scope='voice_pilot'").get()||null}
  addTranscriptSegment(s){this.db.prepare(`INSERT OR IGNORE INTO transcript_segments(call_id,session_id,event_id,speaker,start_ms,end_ms,arrival_seq,received_at,delta,phase,delivery) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(s.call_id,s.session_id,s.event_id,s.speaker,s.start_ms,s.end_ms,s.arrival_seq,s.received_at,s.delta,s.phase,s.delivery)}
  getTranscript(id){return this.db.prepare('SELECT * FROM transcript_segments WHERE call_id=? ORDER BY arrival_seq').all(id)}
  getReviewedHistory(contactId){return this.db.prepare(`SELECT r.call_id, json_extract(COALESCE(r.corrected_semantic_json,p.semantic_json),'$.summary.text') summary, r.review_id FROM reviews r LEFT JOIN post_call_results p ON p.result_id=r.result_id WHERE r.applied=1 AND r.decision IN ('accept','correct') AND EXISTS(SELECT 1 FROM calls c WHERE c.call_id=r.call_id AND c.contact_id=?) ORDER BY r.reviewed_at DESC LIMIT 3`).all(contactId).reverse().filter(x=>x.summary)}
  createResult(result){this.db.prepare(`INSERT INTO post_call_results(result_id,call_id,contact_id,company_id,transcript_sha256,created_at,extractor_model,extractor_prompt_version,schema_version,status,error_code,semantic_json,needs_review,review_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(result.result_id,result.call_id,result.contact_id,result.company_id,result.transcript_sha256,result.created_at,result.extractor_model,result.extractor_prompt_version,result.schema_version,result.status,result.error_code,result.semantic?j(result.semantic):null,result.needs_review?1:0,result.review_id);return result}
  updateResult(id,{status,errorCode=null,semantic=null,needsReview=true}){this.db.prepare('UPDATE post_call_results SET status=?,error_code=?,semantic_json=?,needs_review=? WHERE result_id=?').run(status,errorCode,semantic?j(semantic):null,needsReview?1:0,id)}
  getResult(id){const r=this.db.prepare('SELECT * FROM post_call_results WHERE result_id=?').get(id);return r?{...r,semantic:p(r.semantic_json),needs_review:!!r.needs_review}:null}
  setAnsweredReviewHold(callId){return this.tx(()=>{const c=this.db.prepare('SELECT target_e164 FROM calls WHERE call_id=?').get(callId);if(!c)return;this.db.prepare('UPDATE contacts SET review_pending=1,last_call_id=?,last_attempt_at=?,updated_at=? WHERE phone_e164=?').run(callId,this.now(),this.now(),c.target_e164)})}
  finalizeCall(callId,{cleanupState,telephonyOutcome,terminationReason,processingStatus='ok',transcriptEnvelope,audioStats,openaiFinalization='unconfirmed',latestUsageSeconds=null,finalUsageSeconds=null,answeredAt=null,mediaReadyAt=null,ariCause=null,dialstatus=null,endObservedAt=null}){return this.tx(()=>{
    const c=this.db.prepare('SELECT state,started_at,answered_at,target_e164 FROM calls WHERE call_id=?').get(callId);if(!c)throw new Error('Call not found.');if(c.state==='terminal')return this.getCall(callId);
    const at=this.now(),end=endObservedAt||at,ans=c.answered_at||answeredAt||null;
    const total=c.started_at&&Number.isFinite(Date.parse(end)-Date.parse(c.started_at))?Math.max(0,Date.parse(end)-Date.parse(c.started_at)):null;
    const talk=ans&&Number.isFinite(Date.parse(end)-Date.parse(ans))?Math.max(0,Date.parse(end)-Date.parse(ans)):null;
    this.updateCall(callId,{state:'terminal',answeredAt:ans,mediaReadyAt,endObservedAt:end,finalizedAt:at,cleanupState,telephonyOutcome,terminationReason,ariCause,dialstatus,talkDurationMs:talk,totalDurationMs:total,processingStatus,transcriptState:transcriptEnvelope.state,transcriptEnvelope,audioStats,openaiFinalization,latestUsageSeconds,finalUsageSeconds,reviewRequired:telephonyOutcome==='answered'});
    this.addEvent(callId,'terminal');if(telephonyOutcome==='answered')this.db.prepare('UPDATE contacts SET review_pending=1,last_call_id=?,last_attempt_at=?,updated_at=? WHERE phone_e164=?').run(callId,at,at,c.target_e164);else this.db.prepare('UPDATE contacts SET last_call_id=?,last_attempt_at=?,updated_at=? WHERE phone_e164=?').run(callId,at,at,c.target_e164);
    this.releaseLock(callId);return this.getCall(callId)
  })}
  finalizeInterruptedRecovery(callId,{cleanupState,telephonyOutcome,transcriptEnvelope,audioStats,openaiFinalization='unconfirmed'}){return this.tx(()=>{
    const c=this.db.prepare('SELECT state,started_at,answered_at,target_e164 FROM calls WHERE call_id=?').get(callId);if(!c)throw new Error('Call not found.');const at=this.now(),allAbsent=Object.values(cleanupState).every(x=>x==='absent');
    this.updateCall(callId,{state:'terminal',finalizedAt:at,cleanupState,telephonyOutcome,terminationReason:'process_interrupted',processingStatus:'interrupted',transcriptState:transcriptEnvelope.state,transcriptEnvelope,audioStats,openaiFinalization,reviewRequired:telephonyOutcome==='answered'});
    if(c.state!=='terminal'){this.addEvent(callId,'recovery',{source:'recovery'});this.addEvent(callId,'terminal',{source:'recovery'});const attempt=c.started_at||at;if(telephonyOutcome==='answered')this.db.prepare('UPDATE contacts SET review_pending=1,last_call_id=?,last_attempt_at=?,updated_at=? WHERE phone_e164=?').run(callId,attempt,at,c.target_e164);else this.db.prepare('UPDATE contacts SET last_call_id=?,last_attempt_at=?,updated_at=? WHERE phone_e164=?').run(callId,attempt,at,c.target_e164);}
    if(allAbsent)this.releaseLock(callId);return this.getCall(callId)
  })}
  pendingRecovery(){return this.db.prepare("SELECT call_id,phone_channel_id,media_channel_id,bridge_id,cleanup_state_json,state,originate_intent_at,originate_dispatched_at FROM calls WHERE state IN ('starting','dialing','answered','ending') OR (state='terminal' AND (json_extract(cleanup_state_json,'$.phone')<>'absent' OR json_extract(cleanup_state_json,'$.media')<>'absent' OR json_extract(cleanup_state_json,'$.bridge')<>'absent')) ORDER BY prepared_at").all()}
  applyReview(review){return this.tx(()=>{const c=this.db.prepare('SELECT * FROM contacts WHERE contact_id=(SELECT contact_id FROM calls WHERE call_id=?)').get(review.call_id);if(!c)throw new Error('Contact not found for review.');if(c.revision!==review.expected_contact_revision)throw Object.assign(new Error('Review CAS conflict.'),{code:'review_conflict'}); if(this.db.prepare('SELECT 1 FROM reviews WHERE review_id=?').get(review.review_id))throw new Error('Duplicate review id.'); const upd=review.contact_updates||{}; const fields=[];const vals=[];for(const[k,col]of [['person_name','person_name'],['role_title','role_title'],['phone_e164','phone_e164']])if(upd[k]!=null){fields.push(`${col}=?`);vals.push(upd[k])} let rev=c.revision;if(fields.length||review.accepted_next_action){rev++;fields.push('revision=?');vals.push(rev)} if(review.accepted_next_action){fields.push('next_action_json=?');vals.push(j(review.accepted_next_action))} if(review.dnc_action==='confirm_block'){fields.push("dnc_state='confirmed'");fields.push("permission_state='blocked'");fields.push('authorization_id=NULL')} else if(review.dnc_action==='clear_hold'&&c.dnc_state!=='confirmed'){fields.push("dnc_state='clear'");fields.push('dnc_reason=NULL')} fields.push('review_pending=0','updated_at=?');vals.push(this.now()); this.db.prepare(`UPDATE contacts SET ${fields.join(',')} WHERE contact_id=?`).run(...vals,c.contact_id); this.db.prepare(`INSERT INTO reviews(review_id,call_id,result_id,expected_contact_revision,actor_json,reviewed_at,decision,dnc_action,corrected_semantic_json,accepted_next_action_json,contact_updates_json,notes,evidence_event_ids_json,applied) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,1)`).run(review.review_id,review.call_id,review.result_id,review.expected_contact_revision,j(review.actor),review.reviewed_at,review.decision,review.dnc_action,review.corrected_semantic?j(review.corrected_semantic):null,review.accepted_next_action?j(review.accepted_next_action):null,j(review.contact_updates),review.notes,j(review.evidence_event_ids)); if(review.result_id)this.db.prepare('UPDATE post_call_results SET review_id=? WHERE result_id=?').run(review.review_id,review.result_id);return this.getContact(c.contact_id)})}
  exportAll(){const q=(t)=>this.db.prepare(`SELECT * FROM ${t}`).all();return {schema_version:'1',exported_at:this.now(),companies:q('companies'),contacts:q('contacts'),authorizations:q('authorizations'),calls:q('calls'),call_events:q('call_events'),transcript_segments:q('transcript_segments'),post_call_results:q('post_call_results'),reviews:q('reviews')}}
}
